### ISSUE TITLE
Compass Doesn't Work - Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by umkhan65** [rahulhaque/compass-react-native-non-expo#1]
Your project is working fine but when I used the same code in a new code compass doesn't work. It gives this warning "Possible Unhandled Promise Rejection(id: 0): TypeError: undefined is not a constructor (evaluating 'new _reactNativeSensors.Mangetometer({ updateInterval: 100})')"

**Comment by rahulhaque** [comment]
Did you install 'react-native-sensors' properly and configured your iOS/Gradle dependencies? The latest 'react-native-sensors' library includes many changes. Try with the version used in mine.

**Comment by umkhan65** [comment]
I have tried react-native-sensor@4.1.0, the one you're using and I have configured gradle dependencies
This doesn't solve the issue

**Comment by umkhan65** [comment]
can you please try running this with latest versions and find out where the issue is? I would really appreciate it.

**Comment by rahulhaque** [comment]
I would love to update the app. But, currently I am on a tight schedule with my other projects. I will look upon this issue when I get enough time. If you come across something, feel free to share the solution for others to work out.

**Comment by umkhan65** [comment]
Thanks for considering my request

**Comment by rahulhaque** [comment]
@umkhan65 the app is updated to use the latest version of `react-native` and `react-native-sensors`

**Comment by rahulhaque** [comment]
@umkhan65 the app is updated to use the latest version of `react-native` and `react-native-sensors` I hope you can now figure out the errors you were facing.

**Comment by firofame** [comment]
@rahulhaque @umkhan65 The values from react-native-sensor are not consistent across Android & ios.

I ended up creating my own package, it's much lighter than react-native-sensor and much faster since the calculations are done on the native side.

check it out:
https://github.com/firofame/react-native-compass-heading

**Comment by rahulhaque** [comment]
@firofame You have to provide proof on the statement you've just made about consistency of the `react-native-sensors` data. I found them consistent enough to be worked with. I would like to know what issues you've faced with those.

**Comment by rahulhaque** [comment]
Closing the issue due to inactivity.
